"""empty message

Revision ID: 2b68f1a89dc5
Revises: a9854189b1ac
Create Date: 2021-05-19 01:47:40.930343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b68f1a89dc5'
down_revision = 'a9854189b1ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('task', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
